-- history_buffer.vhd
--   640-deep one-sample-per-frame circular buffer of past sensor
--   state, used by the strip chart. Each entry packs:
--       bits  7..0  : range_in (inches; 0 = no sample)
--       bits 15..8  : als_value (lux 0..255)
--       bits 17..16 : ambient_mode (00/01/10/11 = NIGHT/DIM/DAY/BRIGHT)
--       bits 19..18 : severity if a contact was logged this frame
--       bit  20     : event flag (1 = a contact was logged this frame)
--       bits 31..21 : reserved
--   ref: Xilinx Block Memory Generator PG058. The actual storage is a
--        BMG-IP simple dual-port RAM (port A write, port B read);
--        Vivado allocates one BRAM36 underneath. Generated from
--        scripts/build.tcl, no .xci is committed.
--
--   Lives in clk_pixel. Inputs are already CDC'd to clk_pixel by the
--   parent. The "frame tick" is the rising edge of vsync_in: we latch
--   any log_pulse that happened during the active frame, then write
--   one packed sample at end-of-frame and advance the write pointer.
--   Read port returns a sample one clock after the column index is
--   issued (Lab 4 / Lab 5 BRAM read latency).

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity history_buffer is
    generic (
        N_COLS : positive := 640
    );
    port (
        clk_pixel        : in  std_logic;
        rst              : in  std_logic;

        range_in         : in  unsigned(7 downto 0);
        als_value        : in  unsigned(7 downto 0);
        ambient_mode     : in  unsigned(1 downto 0);
        log_pulse_pixel  : in  std_logic;
        sev_value        : in  unsigned(1 downto 0);

        vsync_in         : in  std_logic;

        rd_col           : in  unsigned(9 downto 0);

        rd_range         : out unsigned(7 downto 0);
        rd_als           : out unsigned(7 downto 0);
        rd_ambient       : out unsigned(1 downto 0);
        rd_severity      : out unsigned(1 downto 0);
        rd_event         : out std_logic
    );
end entity;

architecture rtl of history_buffer is
    constant ADDR_BITS : positive := 10;
    constant DATA_BITS : positive := 32;

    -- BMG IP component (generated by scripts/build.tcl).
    component history_bram_ip
        port (
            clka  : in  std_logic;
            wea   : in  std_logic_vector(0 downto 0);
            addra : in  std_logic_vector(ADDR_BITS-1 downto 0);
            dina  : in  std_logic_vector(DATA_BITS-1 downto 0);
            clkb  : in  std_logic;
            addrb : in  std_logic_vector(ADDR_BITS-1 downto 0);
            doutb : out std_logic_vector(DATA_BITS-1 downto 0)
        );
    end component;

    signal wr_addr   : unsigned(ADDR_BITS-1 downto 0) := (others => '0');
    signal vsync_d   : std_logic := '1';

    signal ev_pending  : std_logic := '0';
    signal sev_pending : unsigned(1 downto 0) := (others => '0');

    signal mem_we       : std_logic_vector(0 downto 0) := "0";
    signal mem_wdata    : std_logic_vector(DATA_BITS-1 downto 0) := (others => '0');
    signal mem_waddr_v  : std_logic_vector(ADDR_BITS-1 downto 0);

    signal rd_addr_r : unsigned(ADDR_BITS-1 downto 0) := (others => '0');
    signal rd_data   : std_logic_vector(DATA_BITS-1 downto 0);
begin

    -- Write side. Latch any log_pulse during the frame, then write
    -- the packed sample on the vsync rising edge (end of vblank, safe
    -- to write because active video has just resumed).
    process(clk_pixel)
        variable wdat : std_logic_vector(DATA_BITS-1 downto 0);
    begin
        if rising_edge(clk_pixel) then
            mem_we <= "0";

            if rst = '1' then
                wr_addr     <= (others => '0');
                vsync_d     <= '1';
                ev_pending  <= '0';
                sev_pending <= (others => '0');
                mem_wdata   <= (others => '0');
            else
                vsync_d <= vsync_in;

                if log_pulse_pixel = '1' then
                    ev_pending  <= '1';
                    sev_pending <= sev_value;
                end if;

                if vsync_d = '0' and vsync_in = '1' then
                    wdat(7 downto 0)   := std_logic_vector(range_in);
                    wdat(15 downto 8)  := std_logic_vector(als_value);
                    wdat(17 downto 16) := std_logic_vector(ambient_mode);
                    wdat(19 downto 18) := std_logic_vector(sev_pending);
                    wdat(20)           := ev_pending;
                    wdat(31 downto 21) := (others => '0');

                    mem_wdata <= wdat;
                    mem_we    <= "1";

                    if wr_addr = to_unsigned(N_COLS-1, ADDR_BITS) then
                        wr_addr <= (others => '0');
                    else
                        wr_addr <= wr_addr + 1;
                    end if;

                    ev_pending  <= '0';
                    sev_pending <= (others => '0');
                end if;
            end if;
        end if;
    end process;

    mem_waddr_v <= std_logic_vector(wr_addr);

    -- Read side: rd_addr = (wr_addr + rd_col) mod N_COLS so column 0
    -- is the oldest sample (left edge) and column N-1 is newest.
    process(clk_pixel)
        variable sum : unsigned(ADDR_BITS downto 0);
    begin
        if rising_edge(clk_pixel) then
            sum := resize(wr_addr, ADDR_BITS+1) + resize(rd_col, ADDR_BITS+1);
            if sum >= to_unsigned(N_COLS, ADDR_BITS+1) then
                rd_addr_r <= resize(sum - to_unsigned(N_COLS, ADDR_BITS+1),
                                    ADDR_BITS);
            else
                rd_addr_r <= resize(sum, ADDR_BITS);
            end if;
        end if;
    end process;

    u_bram : history_bram_ip
        port map (
            clka  => clk_pixel,
            wea   => mem_we,
            addra => mem_waddr_v,
            dina  => mem_wdata,
            clkb  => clk_pixel,
            addrb => std_logic_vector(rd_addr_r),
            doutb => rd_data );

    rd_range    <= unsigned(rd_data(7 downto 0));
    rd_als      <= unsigned(rd_data(15 downto 8));
    rd_ambient  <= unsigned(rd_data(17 downto 16));
    rd_severity <= unsigned(rd_data(19 downto 18));
    rd_event    <= rd_data(20);

end architecture;
